rtmp{
    server {
        listen ${RTMP_PORT}; # Puerto RTMP
        chunk_size 4096; # Tamaño del chunk del stream
        allow publish all; # Permitir a cualquier cliente publicar streams
        
        application hls{
            live on; # Habilitar el modo en vivo
            record off; # Deshabilitar grabación de streams

            hls on; # Habilitar HLS
            hls_path /tmp/hls; # Ruta para almacenar los segmentos HLS
            hls_fragment 1; # Duración de cada fragmento HLS

        
        }

    }
}